'use client';
import PrivacyTipOutlinedIcon from '@mui/icons-material/PrivacyTipOutlined';
import LegalLayout, { LegalContent } from '../../components/legal/LegalLayout';
import { useLegalLang } from '../../lib/legalLang';

const PT: LegalContent = {
  kicker: 'Privacidade',
  title: 'Política de Privacidade',
  subtitle: 'Como a plataforma recolhe, utiliza, conserva e protege os dados pessoais dos seus utilizadores.',
  updated: 'Versão: agosto de 2026 · leitura recomendada antes da utilização',
  sections: [
    { heading: '1. Identificação do responsável pelo tratamento', paragraphs: ['A presente Política de Privacidade aplica-se à plataforma digital e a todas as ferramentas disponibilizadas sob a mesma família de serviços, incluindo ConvertAll, BackCut, CompressHub, DocForge, EditPDF Studio, QRForge, RecCast e ResumeForge, bem como às respectivas interfaces web, aplicações, páginas de suporte e canais oficiais.', 'O responsável pelo tratamento é a entidade proprietária e operadora da plataforma, identificada para efeitos legais como [NOME LEGAL DA ENTIDADE], com sede em [MORADA COMPLETA], número de identificação fiscal/registo [NÚMERO], e contacto de privacidade [EMAIL DE PRIVACIDADE]. Estes elementos devem ser preenchidos pela entidade antes da publicação definitiva desta política.'] },
    { heading: '2. Âmbito e aceitação', paragraphs: ['Esta política explica quais os dados pessoais tratados quando o utilizador visita a plataforma, cria uma conta, utiliza uma ferramenta, subscreve um plano, contacta o suporte ou interage com os canais oficiais. O tratamento é realizado de acordo com a legislação aplicável à situação concreta do utilizador, incluindo, quando aplicável, o Regulamento Geral sobre a Protecção de Dados (RGPD) e a legislação nacional complementar.', 'Ao utilizar a plataforma, o utilizador declara ter lido esta política. Quando a lei exigir consentimento específico, o consentimento será solicitado separadamente, de forma livre, específica, informada e inequívoca. A utilização dos serviços não transforma informação contratual ou legal em consentimento para finalidades opcionais.'] },
    { heading: '3. Dados que podem ser tratados', list: ['Dados de identificação e conta, como nome, nome de utilizador, endereço de correio electrónico, credenciais protegidas e idioma preferido.', 'Dados de subscrição e facturação, como plano seleccionado, estado da subscrição, datas de activação ou expiração, identificadores de transacção e informação necessária para conciliação do pagamento. Os dados completos do cartão ou de outros meios de pagamento são tratados pelo processador de pagamentos aplicável, quando existente.', 'Dados técnicos e de segurança, como endereço IP, navegador, sistema operativo, dispositivo, data e hora de acesso, identificadores de sessão, registos de autenticação, erros e eventos necessários à prevenção de fraude e abuso.', 'Conteúdos fornecidos pelo utilizador, como ficheiros, imagens, PDFs, documentos, gravações, textos, CVs, códigos QR e metadados associados, apenas na medida necessária para executar a operação solicitada.', 'Dados de comunicação, como mensagens dirigidas ao suporte, anexos, preferências e informação necessária para responder ao pedido.', 'Dados de utilização, como ferramenta utilizada, operação solicitada, estado técnico do processamento, consumo de quotas e histórico operacional.'] },
    { heading: '4. Finalidades do tratamento', list: ['Criar, autenticar, manter e proteger a conta do utilizador.', 'Executar as operações solicitadas nas ferramentas, incluindo converter, comprimir, editar, gerar, extrair, redimensionar, assinar, gravar, organizar, criar QR Codes e produzir CVs ou documentos.', 'Processar subscrições, gerir acesso a funcionalidades, aplicar limites de utilização, emitir informação operacional e tratar pedidos de suporte.', 'Detectar, investigar e prevenir fraude, acesso não autorizado, malware, abuso da plataforma, violações de direitos e incidentes de segurança.', 'Manter, diagnosticar e melhorar a estabilidade, disponibilidade, desempenho, acessibilidade e segurança dos serviços.', 'Cumprir obrigações legais, fiscais, contabilísticas, judiciais ou de cooperação com autoridades competentes.', 'Enviar comunicações estritamente necessárias à prestação do serviço. Comunicações comerciais só serão enviadas quando exista base legal adequada e, quando necessário, consentimento.'] },
    { heading: '5. Fundamentos jurídicos', paragraphs: ['Quando aplicável, o tratamento baseia-se na execução de um contrato ou de diligências pré-contratuais, no cumprimento de obrigações legais, no interesse legítimo da plataforma — ponderado com os direitos e liberdades do utilizador — ou no consentimento. O fundamento concreto pode variar conforme o dado, a finalidade, o país do utilizador e a relação estabelecida.', 'Quando o tratamento depender de consentimento, este pode ser retirado a qualquer momento. A retirada não afecta a licitude do tratamento realizado antes dela, nem impede os tratamentos que tenham fundamento jurídico autónomo.'] },
    { heading: '6. Ficheiros e conteúdos submetidos', paragraphs: ['A plataforma trata os ficheiros e conteúdos submetidos exclusivamente para disponibilizar a operação escolhida, cumprir instruções do utilizador, manter a segurança e cumprir obrigações legais. O utilizador conserva os direitos que lhe pertençam sobre o conteúdo que submete ou gera, sem prejuízo dos direitos exclusivos da plataforma sobre o software, código, arquitectura, interface, marcas, design, documentação e demais elementos proprietários.', 'O utilizador deve assegurar que possui autorização para carregar, processar, converter, partilhar ou exportar qualquer conteúdo e que não utiliza a plataforma para violar confidencialidade, direitos de autor, direitos de imagem, segredo comercial, protecção de dados ou qualquer outra norma aplicável.'] },
    { heading: '7. Conservação e eliminação', paragraphs: ['Os dados são conservados pelo período necessário às finalidades para que foram recolhidos, ao cumprimento de obrigações legais, à resolução de litígios e à defesa de direitos. Ficheiros temporários poderão ser eliminados após a conclusão do processamento ou depois do prazo operacional indicado na ferramenta. Rascunhos, partilhas e históricos poderão permanecer até serem eliminados pelo utilizador, até ao termo da finalidade ou até ao limite de conservação aplicável.', 'Após o termo do período relevante, os dados serão eliminados, anonimizados ou isolados, salvo quando a conservação seja necessária por obrigação legal ou para o exercício e defesa de direitos. Cópias de segurança podem conservar dados por um período técnico adicional, ficando sujeitas a controlos de acesso e eliminação cíclica.'] },
    { heading: '8. Prestadores e destinatários', paragraphs: ['A plataforma pode recorrer a prestadores que actuem como subcontratantes ou prestadores técnicos, incluindo alojamento, armazenamento, autenticação, processamento de pagamentos, entrega de correio electrónico, monitorização, segurança e infraestrutura. Esses prestadores só devem tratar dados segundo instruções documentadas, com medidas de confidencialidade e segurança adequadas.', 'Os dados podem ser comunicados a autoridades públicas, tribunais, consultores profissionais ou terceiros quando tal seja exigido por lei, necessário para proteger direitos, investigar fraude, cumprir uma ordem válida ou executar uma operação solicitada pelo utilizador. A plataforma não vende dados pessoais a terceiros.'] },
    { heading: '9. Transferências internacionais', paragraphs: ['Quando um prestador ou infraestrutura se encontrar fora do país do utilizador, a transferência será realizada apenas quando existir mecanismo jurídico adequado, como decisão de adequação, cláusulas contratuais-tipo, regras vinculativas ou outro fundamento reconhecido pela legislação aplicável. O utilizador pode solicitar informação adicional sobre as salvaguardas aplicadas através do contacto de privacidade.'] },
    { heading: '10. Direitos dos titulares', list: ['Solicitar confirmação sobre a existência de tratamento e acesso aos dados pessoais.', 'Pedir rectificação de dados incompletos, inexatos ou desactualizados.', 'Solicitar apagamento quando não exista fundamento legal para a conservação.', 'Solicitar limitação do tratamento em situações previstas na lei.', 'Opor-se ao tratamento baseado em interesse legítimo ou à utilização para marketing directo.', 'Solicitar a portabilidade dos dados quando tecnicamente aplicável.', 'Retirar consentimentos anteriormente prestados.', 'Apresentar reclamação à autoridade de controlo competente, sem prejuízo de contactar primeiro a plataforma para facilitar a resolução.'], note: 'Os pedidos devem ser enviados para [EMAIL DE PRIVACIDADE], com informação suficiente para confirmar a identidade do requerente. A plataforma responderá dentro dos prazos legais aplicáveis e poderá solicitar dados adicionais para evitar divulgação indevida.' },
    { heading: '11. Segurança', paragraphs: ['São aplicadas medidas técnicas e organizativas proporcionais ao risco, incluindo controlo de acesso, autenticação, segregação de dados quando aplicável, cifragem em trânsito, registos de auditoria, limitação de privilégios, cópias de segurança e procedimentos de resposta a incidentes. Nenhum sistema ligado à Internet pode garantir segurança absoluta; por isso, o utilizador deve manter as credenciais confidenciais e comunicar imediatamente qualquer suspeita de acesso indevido.'] },
    { heading: '12. Cookies e tecnologias semelhantes', paragraphs: ['A plataforma pode utilizar cookies estritamente necessários para sessão, segurança, idioma, preferências, funcionamento técnico e prevenção de fraude. Cookies opcionais de análise ou marketing só devem ser utilizados mediante a escolha exigida pela lei aplicável. Mais informação consta da Política de Cookies disponível na plataforma.'] },
    { heading: '13. Menores', paragraphs: ['Os serviços não são dirigidos a menores que não tenham capacidade legal para contratar ou prestar os consentimentos exigidos. Quando a plataforma tenha conhecimento razoável de que recolheu dados de um menor em violação da lei aplicável, adoptará medidas adequadas para eliminar ou restringir esses dados.'] },
    { heading: '14. Alterações à política', paragraphs: ['Esta política pode ser actualizada para reflectir alterações legais, técnicas, operacionais ou de organização. A data e a versão serão actualizadas no topo da página. Alterações materialmente relevantes serão comunicadas por meios adequados, quando exigido. A continuação da utilização após a entrada em vigor da nova versão significa apenas que o utilizador tomou conhecimento da actualização; qualquer consentimento adicional será solicitado separadamente quando necessário.'] },
    { heading: '15. Contacto', paragraphs: ['Para exercer direitos, esclarecer dúvidas, comunicar um incidente de privacidade ou solicitar informação sobre subcontratantes e transferências, contacte [EMAIL DE PRIVACIDADE]. Para assuntos gerais, utilize [EMAIL DE SUPORTE].'] },
  ],
};
export default function PrivacyPage(){ const lang=useLegalLang(); return <LegalLayout content={PT} icon={<PrivacyTipOutlinedIcon style={{fontSize:26,color:'var(--color-primary)'}}/>}/>; }
